Fix tests module
Compiling the tests module fails because of a missing import:

error[E0433]: failed to resolve: use of undeclared type or module `aes_ctr`
   --> src/decrypter.rs:128:6
    |
128 |     use aes_ctr::stream_cipher::NewStreamCipher;
    |         ^^^^^^^ use of undeclared type or module `aes_ctr`

It turned out, however, that NewStreamCipher is never used. Therefore,
it is sufficient to remove the problematic import line.

warning: unused import: `aes_ctr::stream_cipher::NewStreamCipher`
   --> src/decrypter.rs:128:6
    |
128 |     use aes_ctr::stream_cipher::NewStreamCipher;
    |         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    |